apiVersion: v1
kind: Service
metadata:
  name: creditsservice
  labels:
    app: creditsservice
    service: creditsservice
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    service: creditsservice